# Generated by Django 3.2.11 on 2022-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Withdrawn (will be ignored by the interview scheduler)'),
        ),
    ]
